# Generated by Django 5.0.3 on 2024-07-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auth_provider',
            field=models.CharField(default='email', max_length=20),
        ),
    ]
