# Generated by Django 5.0.3 on 2024-07-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
